/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./src/components/auth/Auth.vue')['default']
    AuthLogin: typeof import('./src/components/auth/authLogin.vue')['default']
    AuthRegister: typeof import('./src/components/auth/authRegister.vue')['default']
    AuthVerify: typeof import('./src/components/auth/authVerify.vue')['default']
    Login: typeof import("./src/components/auth/authLogin.vue")["default"]
    Otp: typeof import("./src/components/auth/Otp.vue")["default"]
    Register: typeof import("./src/components/auth/Register.vue")["default"]
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import("./src/components/test.vue")["default"]
  }
}
